gg:
  jte:
    development-mode: true
spring:
  application:
    name: CoffeeVenderApi
  datasource:
    url: jdbc:postgresql://localhost:15432/coffee_db
    driver-class-name: org.postgresql.Driver
    username: coffee_user
    password: asdf1234!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[default_schema]': coffee_vender
        '[format_sql]': true  
server:
  port: 8080
