gg:
  jte:
    development-mode: true
spring:
  application:
    name: CoffeeVenderApi
  datasource:
    url: ${COFFEEVENDER_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${COFFEEVENDER_DATASOURCE_USERNAME}
    password: ${COFFEEVENDER_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[default_schema]': coffee_vender
        '[format_sql]': true  
server:
  port: 8080
